name: CI (Makefile)

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config git

      # vcpkg est cloné/bootstrappé par ton CMake (depuis external/vcpkg).
      # On le cache pour accélérer les builds suivants.
      - name: Cache vcpkg directory
        uses: actions/cache@v4
        with:
          path: external/vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Build (Makefile)
        run: make build

      - name: Run tests (ctest)
        run: ctest --test-dir build --output-on-failure

      - name: Upload build dir on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build
