name: CI - Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vcpkg folder
        uses: actions/cache@v4
        with:
          path: |
            external/vcpkg/installed
            external/vcpkg/buildtrees
            external/vcpkg/downloads
          key: v1-${{ runner.os }}-vcpkg-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            v1-${{ runner.os }}-vcpkg-

      - name: Install system deps (OpenGL/X11 + headless)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build pkg-config \
            xorg-dev libglu1-mesa-dev xvfb
      
      # Bootstrap vcpkg AVANT cmake
      - name: Bootstrap vcpkg (local to repo)
        run: |
          mkdir -p external
          if [ ! -d external/vcpkg ]; then
            git clone https://github.com/microsoft/vcpkg.git external/vcpkg
          fi
          ./external/vcpkg/bootstrap-vcpkg.sh
      
      # Configure en indiquant explicitement le toolchain
      - name: Configure (CMake)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$PWD/external/vcpkg/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: cmake --build build --config Release -- -j 3
      
      - name: Run tests (ctest under Xvfb)
        run: xvfb-run -a -s "-screen 0 1920x1080x24" ctest --test-dir build --output-on-failure
            