name: CI - Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      CMAKE_BUILD_TYPE: Release
      CTEST_OUTPUT_ON_FAILURE: 1
      CMAKE_BUILD_PARALLEL_LEVEL: 3
      VCPKG_ROOT: ${{ github.workspace }}/external/vcpkg
      VCPKG_TOOLCHAIN: ${{ github.workspace }}/external/vcpkg/scripts/buildsystems/vcpkg.cmake

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache vcpkg archives (Linux)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: ~/.cache/vcpkg/archives
          key: v1-${{ runner.os }}-vcpkg-${{ hashFiles('**/CMakeLists.txt', '**/vcpkg*.{json,txt}') }}
          restore-keys: |
            v1-${{ runner.os }}-vcpkg-

      - name: Cache vcpkg archives (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4  
        with:
          path: ${{ env.LOCALAPPDATA }}\vcpkg\archives
          key: v1-${{ runner.os }}-vcpkg-${{ hashFiles('**/CMakeLists.txt', '**/vcpkg*.{json,txt}') }}
          restore-keys: |
            v1-${{ runner.os }}-vcpkg-

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential cmake ninja-build pkg-config \
            xorg-dev libglu1-mesa-dev xvfb \
            libasound2-dev libpulse-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libudev-dev

      - name: Install system deps (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install ninja -y

      - name: Prepare vcpkg (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          set -euxo pipefail
          if [ ! -f "${VCPKG_TOOLCHAIN}" ]; then
            rm -rf "${VCPKG_ROOT}"
            git clone https://github.com/microsoft/vcpkg.git "${VCPKG_ROOT}"
            "${VCPKG_ROOT}/bootstrap-vcpkg.sh" -disableMetrics
          fi
          test -f "${VCPKG_TOOLCHAIN}"

      - name: Prepare vcpkg (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (!(Test-Path "${env:VCPKG_TOOLCHAIN}")) {
            if (Test-Path "${env:VCPKG_ROOT}") { Remove-Item -Recurse -Force "${env:VCPKG_ROOT}" }
            git clone https://github.com/microsoft/vcpkg.git "${env:VCPKG_ROOT}"
            & "${env:VCPKG_ROOT}\bootstrap-vcpkg.bat" -disableMetrics
          }
          if (!(Test-Path "${env:VCPKG_TOOLCHAIN}")) { throw "vcpkg toolchain not found" }

      - name: Configure (CMake + Ninja)
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
            -DCMAKE_TOOLCHAIN_FILE="${VCPKG_TOOLCHAIN}" \
            -DOpenGL_GL_PREFERENCE=GLVND

      - name: Dump configure context on failure
        if: failure()
        shell: bash
        run: |
          echo "::group::Tree build/"
          ls -la build || true
          echo "::endgroup::"
          echo "::group::CMakeFiles logs"
          [ -f build/CMakeFiles/CMakeOutput.log ] && tail -n +1 -v build/CMakeFiles/CMakeOutput.log || true
          [ -f build/CMakeFiles/CMakeError.log ] && tail -n +1 -v build/CMakeFiles/CMakeError.log || true
          echo "::endgroup::"

      - name: Build
        run: cmake --build build --config "${CMAKE_BUILD_TYPE}"

      - name: Run tests (Linux headless with Xvfb)
        if: runner.os == 'Linux'
        run: |
          xvfb-run -a -s "-screen 0 1920x1080x24" \
            ctest --test-dir build --output-on-failure -C "${CMAKE_BUILD_TYPE}"

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: ctest --test-dir build --output-on-failure -C "${CMAKE_BUILD_TYPE}"

      - name: Upload build/test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}
          path: |
            build/Testing
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
