name: CI - Build & Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches-ignore: [ main ]  # on peut builder les branches de feature aussi si tu veux

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Optionnel mais recommandé) Cache de vcpkg cloné par ton CMake
      - name: Cache vcpkg folder
        uses: actions/cache@v4
        with:
          path: |
            external/vcpkg/installed
            external/vcpkg/buildtrees
            external/vcpkg/downloads
          key: v1-${{ runner.os }}-vcpkg-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            v1-${{ runner.os }}-vcpkg-

      - name: Install system deps (OpenGL/X11 for raylib, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build pkg-config xorg-dev libglu1-mesa-dev

      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -- -j 3

      - name: Run tests (ctest)
        run: ctest --test-dir build --output-on-failure
