name: Mirroring

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove excluded paths from history
        run: |
          pip install git-filter-repo
          git filter-repo --invert-paths --path .github --force

      - name: Push to mirror
        run: |
          git remote add mirror "${{ vars.MIRROR_URL }}"
          git push --force mirror HEAD:main
